DESCRIPTION
R/broom.helpers-package.R
R/model_get_contrasts.R
R/model_get_model_frame.R
R/model_get_model_matrix.R
R/model_get_xlevels.R
R/tidy_add_contrasts.R
man/model_get_contrasts.Rd
man/model_get_model_frame.Rd
man/model_get_model_matrix.Rd
man/model_get_xlevels.Rd

Adding an example to all Rd files

Updating rd files

---

vignettes/tidy.Rmd

- added details for columns in modified tidy tibble in vignette

Vignette update

---

vignettes/tidy.Rmd

Just fixing a small typo in the vignette. I hope it gets accepted on the first submission!! 🤞 🤞 🤞 🤞

Vignette typo

---

NEWS.md
R/broom.helpers-package.R
R/model_list_terms_levels.R
R/model_list_variables.R
R/tidy_add_term_labels.R
R/tidy_add_variable_labels.R
R/tidy_plus_plus.R
man/model_list_terms_levels.Rd
man/model_list_variables.Rd
man/tidy_add_term_labels.Rd
man/tidy_plus_plus.Rd
tests/testthat/test-add_variable_labels.R
tests/testthat/test-tidy_plus_plus.R

pattern for categorical terms labels

---

R/tidy_add_variable_labels.R
R/tidy_identify_variables.R
R/tidy_select_variables.R
tests/testthat/test-add_term_labels.R
tests/testthat/test-identify_variables.R
tests/testthat/test-select_helpers.R
tests/testthat/test-select_variables.R

For intercepts, populate variable columns with the name of the term

---

DESCRIPTION
NEWS.md

I forgot to update NEWS and increment version number in the select helper PR.

Update NEWS after select helper update

---

R/select_helpers.R
man/select_helpers.Rd

`all_continuous()` now selects all types that begin with `"continuous"` (rather than equals `"continuous"`)

Update to `all_continuous()`

---

.github/workflows/R-CMD-check.yaml

@larmarange thanks for moving emmeans to Suggests! Adding checks for 3.4 in this PR

Add R CMD Checks for R 3.4

---

.github/workflows/R-CMD-check.yaml
tests/testthat/test-add_coefficients_type.R
tests/testthat/test-add_contrasts.R
tests/testthat/test-add_estimate_to_reference_rows.R
tests/testthat/test-add_n.R
tests/testthat/test-add_term_labels.R
tests/testthat/test-add_variable_labels.R
tests/testthat/test-identify_variables.R
tests/testthat/test-model_get_n.R
tests/testthat/test-tidy_plus_plus.R

Ooops, the 3.4 checks failed still.  I'll keep the PR as a draft until I get the 3.4 checks are sorted out!

3.4 Workflow

---

NEWS.md
R/tidy_identify_variables.R
R/tidy_plus_plus.R
man/tidy_identify_variables.Rd
tests/testthat/test-identify_variables.R
tests/testthat/test-tidy_plus_plus.R
vignettes/tidy.Rmd

remove strict arg from tidy_identify_variables()

---

NEWS.md
R/tidy_add_reference_rows.R
tests/testthat/test-add_reference_rows.R

Populating **effect** column when adding reference rows (#117)

---

NEWS.md
R/model_get_model_matrix.R
tests/testthat/test-tidy_plus_plus.R

Bug fix for `nnet::multinom()` models with a binary outcome

---

DESCRIPTION
NEWS.md
R/select_utilities.R
man/dot-formula_list_to_named_list.Rd
tests/testthat/test-select_helpers.R

for RHS
Option added for not allowing such NULL values
fix #137

By default, .formula_list_to_named_list() should accept NULL values 

---

tests/testthat/test-assert_package.R

Unit test fix for checking min version

---

NEWS.md
R/model_identify_variables.R

Avoid an unwanted warning for some `mgcv::gam()` models

---

R/select_utilities.R

`switch()` fix in utilities

---

R/broom.helpers-package.R
R/custom_tidiers.R
R/select_utilities.R
R/tidy_add_coefficients_type.R
R/tidy_add_contrasts.R
R/tidy_add_estimate_to_reference_rows.R
R/tidy_add_header_rows.R
R/tidy_add_n.R
R/tidy_add_pairwise_contrasts.R
R/tidy_add_reference_rows.R
R/tidy_add_term_labels.R
R/tidy_add_variable_labels.R
R/tidy_and_attach.R
R/tidy_disambiguate_terms.R
R/tidy_identify_variables.R
R/tidy_remove_intercept.R
R/tidy_select_variables.R

use cli_abort() instead of stop()

---

.github/workflows/R-CMD-check.yaml
.github/workflows/R-CMD-historic-R-check.yaml
.github/workflows/lint.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml
NEWS.md
R/model_get_pairwise_contrasts.R
R/tidy_add_pairwise_contrasts.R
R/tidy_plus_plus.R
man/model_get_pairwise_contrasts.Rd
man/tidy_add_pairwise_contrasts.Rd
man/tidy_plus_plus.Rd
tests/testthat/test-add_pairwise_contrasts.R

in `tidy_plus_plus()`,
`tidy_add_pairwise_contrasts()` and `model_get_pairwise_contrasts()` allowing
to change the adjustment method used to compute pairwise contrasts
fix #204

New argument `contrasts_adjust`

---

DESCRIPTION
NEWS.md
vignettes/articles/marginal_tidiers.Rmd

vignette update following marginaleffects 0.10.0

---

tests/testthat/test-add_coefficients_type.R
tests/testthat/test-add_contrasts.R
tests/testthat/test-add_header_rows.R
tests/testthat/test-add_n.R
tests/testthat/test-add_reference_rows.R
tests/testthat/test-add_variable_labels.R
tests/testthat/test-identify_variables.R
tests/testthat/test-model_get_n.R

This recommended package may not be available on all installations

Optionally skip tests requiring 'nnet'

---

NEWS.md
tests/testthat/test-add_coefficients_type.R
tests/testthat/test-add_contrasts.R
tests/testthat/test-add_estimate_to_reference_rows.R
tests/testthat/test-add_n.R
tests/testthat/test-add_term_labels.R
tests/testthat/test-add_variable_labels.R
tests/testthat/test-identify_variables.R
tests/testthat/test-model_get_n.R
tests/testthat/test-tidy_plus_plus.R
vignettes/tidy.Rmd

use character string with packageVersion()

---

NEWS.md
R/tidy_plus_plus.R
inst/WORDLIST
man/supported_models.Rd
man/tidy_plus_plus.Rd
tests/testthat/test-tidy_plus_plus.R

new `tidy_post_fun` argument in `tidy_plus_plus()`

---

vignettes/broom-helpers.Rmd

imrpovement of examples in vignette

---

NEWS.md
R/model_get_model_frame.R
R/model_get_model_matrix.R
tests/testthat/test-tidy_plus_plus.R

bug fix for `fixest` models when using a sub-setted data frame
